### ISSUE TITLE
I want to help

### ISSUE THREAD

**Issue by valenok** [eugene-krivosheyev/java-junior#2]
Hello, I'm newbie in Java and I want to learn more about it. If I can be useful in your project, please write me (my e-mail: natka_kolobok@bk.ru). I wish you good luck any way )

**Comment by eugene-krivosheyev** [comment]
Now we do not feel need for external assistance at the moment. Maybe next time.
Thank you!

**Comment by eugene-krivosheyev** [comment]
Please send me your CV at ekrATbk.ru

**Comment by valenok** [comment]
Hello!
Thank you for your replay.
ekrATbk.ru - it doesn't work or I don't understand anything ) and I cann't sent my CV.
And I think it will say not so much (I have no experience in programming. I'm learning it now). I have some experience in testing, but it was 1C, not Java.

**Comment by eugene-krivosheyev** [comment]
“AT” means “@“. So my email is ekr@bk.ru

**Comment by valenok** [comment]
Thank you. I've sent.
